language: perl
perl:
  - "5.20"
  - "5.16"
  - "5.14"
  - "5.12"
services:
  - mysql
addons:
  hosts:
  - 188.166.56.30 rhino_data
env: PERL_MM_USE_DEFAULT=1
before_install:
  - cpan o conf init
  - cpanm CPAN::Uploader
install:
  - cpanm --quiet --notest --skip-satisfied Catalyst::Runtime Module::Install::Catalyst 
  - cpanm --quiet --notest --skip-satisfied Catalyst::Model::DBIC::Schema Catalyst::View::TT MooseX::NonMoose
  - cpanm --quiet --notest --skip-satisfied Catalyst::Action::REST Catalyst::Plugin::Session::State::Cookie
  - cpanm --quiet --notest --skip-satisfied Catalyst::Plugin::Session::Store::File DBIx::Class::PassphraseColumn
  - cpanm --quiet --notest --skip-satisfied Catalyst::Plugin::Authentication Catalyst::Plugin::Authorization::Roles
  - cpanm --quiet --notest --skip-satisfied Catalyst::Authentication::Realm::SimpleDB DBD::mysql
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=j10:c HARNESS_TIMER=1 DBIC_TRACE=1
script:
  - perl Makefile.PL && make test
notifications:
  email:
    - italo.goncales@gmail.com
    - sax.soares@gmail.com
    - felipergama@gmail.com
